### ISSUE TITLE
Questions about "Java Download"

### ISSUE THREAD

**Issue by CEllenvia** [LYOfficial/MinecraftPlayGuide#1]
- The openjdk provided by TUNA is a mirror of Eclipse OpenJDK, Temurin. So in my opinion, it should be mentioned in the description.
- the Origional https://openjdk.org/ should be added into this list too, although because of some reason, the download is SUPER SLOW in China Mainland.
- TUNA mirrors sometimes become so slow since the fair-use policy.(maybe?) USTC mirror may have better performance and can be added after TUNA mirror. https://mirrors.ustc.edu.cn/AdoptOpenJDK

**Comment by LYOfficial** [comment]
感谢指出（话说这是中文文档，可以直接中文发言）
已全部修正
